#version 460
#extension GL_EXT_buffer_reference : require

layout (local_size_x = 16, local_size_y = 16) in;

layout(rgba8,set = 0, binding = 0) uniform image2D color;
layout(rgba16f,set = 0, binding = 1) uniform image2D normal;
layout(rgba16f,set = 0, binding = 2) uniform image2D position;
layout(rgba8,set = 0, binding = 3) uniform image2D final_image;
//4 is now UI image on the render target, s skip oer that to get extra image start
layout(r32f,set = 0, binding = 5) uniform image2D light_map_depth;

struct Component{
	vec4 light_position ;
	vec4 light_color ;
	mat4 light_matrix ;
};

layout(buffer_reference, std430) readonly buffer ComponentBuffer{ 
	Component components[];
};

//push constants block
layout( push_constant ) uniform constants
{	
	mat4 render_matrix;
	vec3 camera_position ;
	ComponentBuffer component_buffer;
} PushConstants;


float sampleShadowMap(vec3 relative_to_light, ivec2 light_map_size){


	vec2 sp = vec2(relative_to_light.x * light_map_size.x,relative_to_light.y * light_map_size.y) ;
	ivec2 isp = ivec2(int(sp.x), int(sp.y)) ;

	float l00 = relative_to_light.z <= imageLoad(light_map_depth, isp).r ? 1 : 0 ;
	float l01 = relative_to_light.z <= imageLoad(light_map_depth, ivec2(isp.x,isp.y+1)).r ? 1 : 0 ;
	float l10 = relative_to_light.z <= imageLoad(light_map_depth, ivec2(isp.x+1,isp.y)).r ? 1 : 0 ;
	float l11 = relative_to_light.z <= imageLoad(light_map_depth, ivec2(isp.x+1,isp.y+1)).r ? 1 : 0 ;

	float t = sp.x-isp.x ;
	float s = sp.y-isp.y ;
	float l = (1-t)*(1-s) * l00 + (1-t)*s*l01 + t*(1-s)*l10 + t*s*l11 ;

	return l ;

}

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	//ivec2 size = imageSize(color);
    vec4 light_color = PushConstants.component_buffer.components[0].light_color ;
	vec4 light_position = PushConstants.component_buffer.components[0].light_position ;
	mat4 light_view = PushConstants.component_buffer.components[0].light_matrix ;
	vec4 raw_p = imageLoad(position, texelCoord) ;
	vec4 raw_color = imageLoad(color, texelCoord) ;
	vec3 raw_normal = normalize(imageLoad(normal, texelCoord).xyz) ;

	
ivec2 light_map_size = imageSize(light_map_depth);
	/*

	
	if(texelCoord.x < light_map_size.x && texelCoord.y < light_map_size.y ){
		vec4 lit_color = imageLoad(light_map_depth,texelCoord) ;
		imageStore(final_image, texelCoord, lit_color*0.05f);
	}else*/

	if(raw_p.w > 0){

		
		vec3 to_light = normalize(light_position.xyz-raw_p.xyz) ;
		float brightness = max(dot(raw_normal,to_light),0);
		vec4 lit_color = imageLoad(final_image, texelCoord); // get the existing light we need to add to


		vec4 light_h = light_view*raw_p ;
		vec3 relative_to_light = vec3(light_h.x/light_h.w, light_h.y/light_h.w, light_h.z/light_h.w ) ;
		relative_to_light.x = (relative_to_light.x+1.0f)*0.5f ; // scale into 0 to 1 texture coordinates
		relative_to_light.y = (relative_to_light.y+1.0f)*0.5f ;

		// If within the spotlight area
		if(relative_to_light.x > 0 && relative_to_light.y > 0 && relative_to_light.x < 1.0f && relative_to_light.y < 1.0f){

			
			
			float l = 0.2*sampleShadowMap(relative_to_light, light_map_size);
			float o = 1.0/light_map_size.x ;
			l+= 0.2 * sampleShadowMap(relative_to_light+vec3(o,o,0), light_map_size);
			l+= 0.2 * sampleShadowMap(relative_to_light+vec3(o,-o,0), light_map_size);
			l+= 0.2 * sampleShadowMap(relative_to_light+vec3(-o,o,0), light_map_size);
			l+= 0.2 * sampleShadowMap(relative_to_light+vec3(-o,-o,0), light_map_size);

			brightness *= l ;
			lit_color.r = lit_color.r + raw_color.r * light_color.r*brightness ;
				lit_color.g = lit_color.g + raw_color.g * light_color.g*brightness ;
				lit_color.b = lit_color.b + raw_color.b * light_color.b*brightness ;

				lit_color.r = min(raw_color.r, lit_color.r) ;
				lit_color.g = min(raw_color.g, lit_color.g) ;
				lit_color.b = min(raw_color.b, lit_color.b) ;
	

			/*
			float map_depth = imageLoad(light_map_depth, sp).r;
			if(relative_to_light.z <= map_depth){ // in front of the shadowed part
				//add the light
				lit_color.r = lit_color.r + raw_color.r * light_color.r*brightness ;
				lit_color.g = lit_color.g + raw_color.g * light_color.g*brightness ;
				lit_color.b = lit_color.b + raw_color.b * light_color.b*brightness ;

				lit_color.r = min(raw_color.r, lit_color.r) ;
				lit_color.g = min(raw_color.g, lit_color.g) ;
				lit_color.b = min(raw_color.b, lit_color.b) ;
			}
			*/
		}
		imageStore(final_image, texelCoord, lit_color); // put the modified light back into the image
	}else{
		imageStore(final_image, texelCoord, raw_color); // no object present, pass through the background color
	}
	
}