#include "SocketTest.h"
#include "VulkanPlugin.h"
#include "Registry.h"
#include "FlagSet.h"

//Loads models from the hard drive on construction
SocketTest::SocketTest(){
	testExtendedSerializer();
	PACKET_ID = registry.registerClass<TestPacket>("TestPacket") ;
}

void SocketTest::run(){
	
	/*
	if (!r->server) {
		r->socket->send(1, r->my_message);
	}*/

	VulkanPlugin* window = getTool<VulkanPlugin>();
	// Check if escape pressed to exit
	if (window->getLastKeyPress() == SDLK_ESCAPE) {
		getTool<FlagSet>()->setInt(AsyncPlugin::SHUTDOWN_FLAG, 1);
	}
}

// Called when switching into this sate before the first time run is claled
void SocketTest::enter(std::shared_ptr<MachineState> from){
	auto server = std::shared_ptr<TCPServerSocket>(new TCPServerSocket()) ;
	server->setPacketReceiver(r.get());
	r->packet.message = "servin!" ;
	r->server = true;
	r->socket = server;
	bool server_success = server->open(4225) ;
	if(server_success){
		
		printf("socket hosting\n");
	}else{ // couldn't open socket so it's probably already open, try to connect to it
		auto client = std::shared_ptr<TCPClientSocket>(new TCPClientSocket());
		client->setPacketReceiver(r.get());
		r->packet.message = "joinin" ;
		r->server = false;
		r->socket = client;
		bool client_success = client->connect("127.0.0.1",4225) ;
		if(client_success){
			printf("socket clienting open\n");
		}
	}
		

}

// Called when switching outof this state after the last time run is called
void SocketTest::exit(std::shared_ptr<MachineState> to){

}

//Called when a packet is received
void SocketTest::Receiver::receivePacket(int sender_id, const std::vector<char>& data){
	try {
	std::shared_ptr<TestPacket> r = static_pointer_cast<TestPacket>(SocketTest::registry.deserializeObj(SocketTest::PACKET_ID, data)) ;


	printf("Got packet from id=%d  name=%s number=%d message=%s: \n", sender_id, r->source.c_str(), r->number, r->message.c_str());
	packet.message = "number++";
	packet.number++;
	std::vector<char> serial = SocketTest::registry.serializeObj(SocketTest::PACKET_ID, &packet) ;
	socket->send(sender_id, serial);
	}
	catch (const std::runtime_error& e) {
		std::cerr << "Caught a runtime error on packet retrieval: " << e.what() << std::endl;
	}
	catch(...){
		std::cerr << "unknown exception on packet retrieval" << std::endl;
	}
}

//Called when a connection is established, 
//sender_id is generated by the socket and can be used to identify recieved packet sources or send data back through the socket
void SocketTest::Receiver::onSocketConnect(int sender_id){
	printf("Connected to %d\n", sender_id);
	if(!server){
		packet.message = "saw connection" ;
		std::vector<char> serial = SocketTest::registry.serializeObj(SocketTest::PACKET_ID, &packet);
		socket->send(sender_id, serial);
	}
}

//Called when a connection is closed, either remotely or because the socket holding it was closed
void SocketTest::Receiver::onSocketClose(int sender_id){
	printf("Closed %d\n", sender_id) ;
}

void SocketTest::testExtendedSerializer(){

	std::vector<char> buffer;

	// --- Test 1: Simple Pair ---
	std::pair<int, std::string> p1 = { 42, "forty-two" };
	serializeArg(buffer, p1);

	const char* data = buffer.data();
	auto p1_out = deserializeArg<std::pair<int, std::string>>(data);
	assert(p1_out.first == 42);
	assert(p1_out.second == "forty-two");
	buffer.clear();

	std::cout << "Pair test passed \n";

	// --- Test 2: Tuple ---
	std::tuple<int, float, std::string> t1 = { 10, 3.14f, "tuple!" };
	serializeArg(buffer, t1);

	data = buffer.data();
	auto t1_out = deserializeArg<std::tuple<int, float, std::string>>(data);
	assert(std::get<0>(t1_out) == 10);
	assert(std::get<1>(t1_out) == 3.14f);
	assert(std::get<2>(t1_out) == "tuple!");
	buffer.clear();

	std::cout << "Tuple test passed \n";

	// --- Test 3: Map ---
	std::map<int, std::string> m1 = { {1, "one"}, {2, "two"}, {3, "three"} };
	serializeArg(buffer, m1);

	data = buffer.data();
	auto m1_out = deserializeArg<std::map<int, std::string>>(data);
	assert(m1_out == m1);
	buffer.clear();

	std::cout << "Map test passed \n";

	// --- Test 4: Unordered Map ---
	std::unordered_map<std::string, int> um1 = { {"apple", 1}, {"banana", 2}, {"cherry", 3} };
	serializeArg(buffer, um1);

	data = buffer.data();
	auto um1_out = deserializeArg<std::unordered_map<std::string, int>>(data);
	assert(um1_out.size() == um1.size());
	for (auto& kv : um1){
		assert(um1_out.at(kv.first) == kv.second);
	}
	buffer.clear();

	std::cout << "Unordered Map test passed \n";

	// --- Test 5: Set ---
	std::set<int> s1 = { 1, 5, 9 };
	serializeArg(buffer, s1);

	data = buffer.data();
	auto s1_out = deserializeArg<std::set<int>>(data);
	assert(s1_out == s1);
	buffer.clear();

	std::cout << "Set test passed \n";

	// --- Test 6: Unordered Set ---
	std::unordered_set<std::string> us1 = { "red", "green", "blue" };
	serializeArg(buffer, us1);

	data = buffer.data();
	auto us1_out = deserializeArg<std::unordered_set<std::string>>(data);
	assert(us1_out.size() == us1.size());
	for (auto& v : us1) assert(us1_out.contains(v));
	buffer.clear();

	std::cout << "Unordered Set test passed \n";

	// --- Test 7: Nested Structure ---
	std::unordered_map<std::string, std::vector<std::pair<int, std::set<std::string>>>> nested;
	nested["group1"] = {
		{1, {"a", "b"}},
		{2, {"x", "y", "z"}}
	};
	nested["group2"] = {
		{10, {"cat", "dog"}},
		{11, {"mouse"}}
	};

	serializeArg(buffer, nested);

	data = buffer.data();
	auto nested_out = deserializeArg<std::unordered_map<std::string, std::vector<std::pair<int, std::set<std::string>>>>>(data);

	assert(nested_out.size() == nested.size());
	for (auto& kv : nested) {
		auto& out_vec = nested_out.at(kv.first);
		auto& in_vec = kv.second;
		assert(out_vec.size() == in_vec.size());
		for (size_t i = 0; i < in_vec.size(); i++) {
			assert(out_vec[i].first == in_vec[i].first);
			assert(out_vec[i].second == in_vec[i].second);
		}
	}
	buffer.clear();

	std::cout << "Nested container test passed \n";

	std::cout << "\nAll serialization tests passed \n";
}