#ifndef _SOCKET_TEST_H_
#define _SOCKET_TEST_H_ 1

#include "MachineState.h"
#include "Sockets.h"
#include "Registry.h"

#include <string>
#include <map>


class SocketTest : public MachineState{

public:
	static inline int PACKET_ID = -1;
	static inline Registry registry ;

	class TestPacket{
	public:
		int number = 0 ;
		std::string source = "a" ;
		std::string message = "message" ;
	};

	class Receiver : public PacketReceiver {
	public: 
		// the socket the data is coming from, could be UDPServerSocket or UDPClientSocket
		std::shared_ptr<Socket> socket ;
		bool server = false;
		TestPacket packet ;
		
		//Called when a packet is received
		void receivePacket(int sender_id, const std::vector<char>& data) override;

		//Called when a connection is established, 
		//sender_id is generated by the socket and can be used to identify recieved packet sources or send data back through the socket
		void onSocketConnect(int sender_id) override;

		//Called when a connection is closed, either remotely or because the socket holding it was closed
		void onSocketClose(int sender_id) override;
	};

	static inline const std::string state_name = "socket_test";


	//Loads models from the hard drive on construction
	SocketTest();

	void run() override;

	// Called when switching into this sate before the first time run is claled
	void enter(std::shared_ptr<MachineState> from) override;

	// Called when switching outof this state after the last time run is called
	void exit(std::shared_ptr<MachineState> to) override;

	

private:
	
	std::shared_ptr<Receiver> r = std::shared_ptr<Receiver>(new Receiver());
	

	void testExtendedSerializer();
};


auto static getStructure(SocketTest::TestPacket& obj) {
	return std::tie(obj.number, obj.source, obj.message);
}

#endif // #ifndef _SOCKET_TEST_H_